# .travis.yml
language: go

go:
- 1.13.x

addons:
  apt:
    packages:
    - rpm
    - snapd
    - nodejs
    - npm

env:
- PATH=/snap/bin:$PATH

install:
- sudo snap install snapcraft --classic

script: echo $TRAVIS_OS_NAME
script: echo $TRAVIS_TAG

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --snapshot
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux