# .travis.yml
language: go

go:
- 1.13.x

addons:
  apt:
    packages:
    - rpm
    - snapd
    - nodejs
    - npm

services:
  - docker

env:
- PATH=/snap/bin:$PATH

before_install:
  - docker build -t vault-token-issuer:1 .
  - docker images

install:
- sudo snap install snapcraft --classic

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux